### ISSUE TITLE
Error:       File "<__array_function__ internals>", line 6, in concatenate

### ISSUE THREAD

**Issue by marcDabad** [marcpaga/esox#2]
Hi Marc, 

this behavior is expected? Do you have any idea why this error can arise?

```
Traceback (most recent call last):      
  File "/home/mdabad/software/esox/esox/scripts/basecall.py", line 255, in <module>
    array_keeper[k] = np.concatenate(v, axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
```

Thanks,

**Comment by marcpaga** [comment]
Strange, this would happen if there were no basecalled guanines, but it should have been handled above to avoid this.

Do you get this error on the demo data or on your data?
If the latter, is the data in multifast5 format? Would it be possible to share perhaps the file that is causing the error to debug?

**Comment by marcDabad** [comment]
Hi Marc, 
they are pod5 to multifast5 files. 
If you send me contact, I can send you an example. 

Thanks,

**Comment by marcpaga** [comment]
You can e-mail me at m.pagesgallego at umcutrecht.nl

**Comment by marcDabad** [comment]
Dear Marc, 

I have double check and our chemistry was r10.4 5khz :facepalm: 

I'll close this issue because I think the problems came because the chemistry. 

Moltes gràcies,
