### ISSUE TITLE
R10.4 5000Hz Chemistry Models in Development?

### ISSUE THREAD

**Issue by andrewgalbraith21** [marcpaga/esox#3]
Hello! 

Great paper and exciting to see nanopore be used to detect 8oxoG. I was wondering if you are planning to develop models on the latest chemistry (R10.4 5000Hz) and if so what the timeline would look like? Thanks

It sounds like nanopore will also be releasing their own models fairly shortly.

**Comment by marcpaga** [comment]
Thank you for your interest. Unfortunately, R10 would require a different oligo design to ensure enough sequence variability, so we are not planning on releasing any other models. If you need an R10 model your best bet is in waiting ONT's model.

**Comment by andrewgalbraith21** [comment]
Hello Marc, makes sense, thanks for letting me know!
